image:
  repository: ipfs/go-ipfs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.10.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

ingressApi:
  enabled: false
    # hosts:
    # - ipfs-api.localhost.localdomain
    # - localhost.localdomain/ipfs-api
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"
    # tls:
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

ingressGateway:
  enabled: false
    # hosts:
    # - ipfs-gateway.localhost.localdomain
    # - localhost.localdomain/ipfs-gateway
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   kubernetes.io/tls-acme: "true"
    # tls:
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

swarmKey: 
bootstrap:

swarm:
  enabled: true
  type: ClusterIP
  # loadBalancerIP: ""
  # externalIP: ""
  ## Further config for service of type NodePort
  ## Default config with empty string "" will assign a dynamic nodePort
  nodePort: ""
  ## If static nodePort configuration is required it can be enabled as below
  ## Configure ports in allowable range (eg. 30000 - 32767 on minikube)
  # nodePort: 34001

resources: {}

persistence:
  enabled: false
  ## ipfs data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  size: "8Gi"
  accessModes:
    - ReadWriteOnce
