{{/*
  Copyright © 2022 Kaleido, Inc.

  SPDX-License-Identifier: Apache-2.0

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://swww.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/}}

{{- if .Values.job.registerContracts.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "firefly-evmconnect.registerContractsJobName" . }}"
  labels:
    {{- include "firefly-evmconnect.labels" . | nindent 4 }}
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 12000
  template:
    spec:
      volumes:
        - name: contracts
          configMap:
            name: {{ include "firefly-evmconnect.fullname" . }}-contracts
        - name: tmp
          emptyDir: {}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: register-contracts
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default (printf "v%s" .Chart.AppVersion) }}"
          command:
          - sh
          - -ce
          - |
{{ .Files.Get  "scripts/ff-register-contracts.sh" | indent 12 }}
          env:
            - name: EVMCONNECT_URL
              value: "http://{{ include "firefly-evmconnect.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}"
            - name: FROM_ADDRESS
              value: {{ .Values.job.registerContracts.from }}
          volumeMounts:
            - name: contracts
              mountPath: /var/lib/ethconnect/contracts
            - name: tmp
              mountPath: /tmp
      restartPolicy: Never
{{- end }}